aws-region: us-gov-west-1

cert-check-git-branch: master
cert-check-git-url: https://github.com/18F/cg-cert-check
github-repo: 18F/cg-cert-check

schedule-interval: 24h

slack-username: cg-cert-check
